BEGIN;

CREATE TABLE IF NOT EXISTS categories (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255) NOT NULL,
  description TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        VARCHAR(255) NOT NULL,
  category_id INTEGER NOT NULL REFERENCES categories (id),
  description TEXT,
  price       NUMERIC(12, 2) NOT NULL CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS suppliers (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_name  VARCHAR(255) NOT NULL,
  supplier_email VARCHAR(254) NOT NULL,
  supplier_phone VARCHAR(50)  NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products_suppliers (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id     INTEGER NOT NULL REFERENCES products (id)  ON DELETE CASCADE,
  supplier_id    INTEGER NOT NULL REFERENCES suppliers (id) ON DELETE CASCADE,
  supplier_price NUMERIC(12, 2) NOT NULL CHECK (supplier_price >= 0),
  supplier_sku   VARCHAR(100) NOT NULL,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (product_id, supplier_id)
);

CREATE TABLE IF NOT EXISTS warehouses (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(255) NOT NULL,
  location   VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS inventory (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id   INTEGER NOT NULL REFERENCES products (id)   ON DELETE CASCADE,
  warehouse_id INTEGER NOT NULL REFERENCES warehouses (id) ON DELETE CASCADE,
  amount       INTEGER NOT NULL DEFAULT 0 CHECK (amount >= 0),
  last_update  TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (product_id, warehouse_id)
);

CREATE TABLE IF NOT EXISTS stock_movements (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id    INTEGER NOT NULL REFERENCES products (id),
  warehouse_id  INTEGER NOT NULL REFERENCES warehouses (id),
  movement_type VARCHAR(20) NOT NULL CHECK (movement_type IN ('RECEIPT', 'SALE')),
  quantity      INTEGER NOT NULL CHECK (quantity > 0),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customers (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name    VARCHAR(255) NOT NULL,
  customer_email   VARCHAR(254) NOT NULL,
  shipping_address TEXT NOT NULL,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  INTEGER NOT NULL REFERENCES customers (id),
  warehouse_id INTEGER NOT NULL REFERENCES warehouses (id),
  status       VARCHAR(20) NOT NULL DEFAULT 'pending'
               CHECK (status IN ('pending', 'processing', 'completed', 'cancelled')),
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders_items (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id   INTEGER NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES products (id),
  quantity   INTEGER NOT NULL CHECK (quantity >= 1),
  price      NUMERIC(12, 2) NOT NULL CHECK (price >= 0)
);

CREATE TABLE IF NOT EXISTS accounts (
  account_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   INTEGER REFERENCES customers (id),
  username      VARCHAR(30)  NOT NULL UNIQUE,
  email         VARCHAR(254) NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  status        VARCHAR(20) NOT NULL DEFAULT 'pending',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS account_verification_tokens (
  token_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id INTEGER NOT NULL REFERENCES accounts (account_id) ON DELETE CASCADE,
  token_hash VARCHAR(64) NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS roles (
  role_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS permissions (
  permission_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id       INTEGER NOT NULL REFERENCES roles (role_id)             ON DELETE CASCADE,
  permission_id INTEGER NOT NULL REFERENCES permissions (permission_id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS account_roles (
  account_id INTEGER NOT NULL REFERENCES accounts (account_id) ON DELETE CASCADE,
  role_id    INTEGER NOT NULL REFERENCES roles (role_id)       ON DELETE CASCADE,
  PRIMARY KEY (account_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_products_category_id        ON products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_suppliers_supplier ON products_suppliers (supplier_id);
CREATE INDEX IF NOT EXISTS idx_inventory_warehouse_id      ON inventory (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_product_id  ON stock_movements (product_id);
CREATE INDEX IF NOT EXISTS idx_stock_movements_warehouse   ON stock_movements (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_orders_customer_id          ON orders (customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_warehouse_id         ON orders (warehouse_id);
CREATE INDEX IF NOT EXISTS idx_orders_items_order_id       ON orders_items (order_id);
CREATE INDEX IF NOT EXISTS idx_orders_items_product_id     ON orders_items (product_id);
CREATE INDEX IF NOT EXISTS idx_accounts_customer_id        ON accounts (customer_id);
CREATE INDEX IF NOT EXISTS idx_account_roles_role_id       ON account_roles (role_id);

INSERT INTO roles (role_id, name) VALUES
  (1, 'Product Manager'),
  (2, 'Category Manager'),
  (3, 'Customer Manager'),
  (4, 'Supplier Manager'),
  (5, 'Warehouse Manager'),
  (6, 'Inventory Manager'),
  (7, 'Ordering Manager'),
  (8, 'Customer'),
  (9, 'Owner')
ON CONFLICT DO NOTHING;

SELECT setval(
  pg_get_serial_sequence('roles', 'role_id'),
  (SELECT MAX(role_id) FROM roles)
);

INSERT INTO permissions (name) VALUES
  ('account.role.grant'),
  ('account.role.read'),
  ('account.role.revoke'),
  ('category.create'),
  ('category.delete'),
  ('category.read'),
  ('category.update'),
  ('customer.create'),
  ('customer.delete'),
  ('customer.read'),
  ('customer.update'),
  ('inventory.adjust'),
  ('inventory.checks'),
  ('inventory.create'),
  ('inventory.delete'),
  ('inventory.low_stock'),
  ('inventory.read'),
  ('inventory.summary'),
  ('inventory.update'),
  ('order.cancel'),
  ('order.create'),
  ('order.delete'),
  ('order.details'),
  ('order.process'),
  ('order.read'),
  ('order.total'),
  ('order.update'),
  ('order.update_status'),
  ('order_item.create'),
  ('order_item.delete'),
  ('order_item.read'),
  ('order_item.update'),
  ('product.create'),
  ('product.delete'),
  ('product.read'),
  ('product.update'),
  ('product_supplier.create'),
  ('product_supplier.delete'),
  ('product_supplier.read'),
  ('product_supplier.update'),
  ('role.create'),
  ('role.delete'),
  ('role.permission.grant'),
  ('role.permission.read'),
  ('role.permission.revoke'),
  ('role.read'),
  ('stock_movement.read'),
  ('supplier.create'),
  ('supplier.delete'),
  ('supplier.read'),
  ('supplier.update'),
  ('warehouse.create'),
  ('warehouse.delete'),
  ('warehouse.read'),
  ('warehouse.update')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
JOIN permissions p
  ON (r.name = 'Owner')
  OR (r.name = 'Product Manager'   AND p.name LIKE 'product.%')
  OR (r.name = 'Category Manager'  AND p.name LIKE 'category.%')
  OR (r.name = 'Customer Manager'  AND p.name LIKE 'customer.%')
  OR (r.name = 'Supplier Manager'  AND (p.name LIKE 'supplier.%' OR p.name LIKE 'product\_supplier.%'))
  OR (r.name = 'Warehouse Manager' AND p.name LIKE 'warehouse.%')
  OR (r.name = 'Inventory Manager' AND (p.name LIKE 'inventory.%' OR p.name = 'stock_movement.read'))
  OR (r.name = 'Ordering Manager'  AND (p.name LIKE 'order.%' OR p.name LIKE 'order\_item.%'))
  OR (r.name = 'Customer'          AND p.name IN ('product.read', 'category.read'))
ON CONFLICT DO NOTHING;

COMMIT;